// <auto-generated />
using System;
using MahoSoft.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MahoSoft.Datos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260929201955_InicialPostgres")]
    partial class InicialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:CollationDefinition:sin_mayusculas", "und-u-ks-level2,und-u-ks-level2,icu,False")
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MahoSoft.Entidades.Archivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Almacen")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PublicId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("SubidoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Tamano")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoMime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.ToTable("Archivos", t =>
                        {
                            t.HasCheckConstraint("CK_Archivos_Tamano", "\"Tamano\" >= 0");
                        });
                });

            modelBuilder.Entity("MahoSoft.Entidades.Banco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .UseCollation("sin_mayusculas");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Bancos");
                });

            modelBuilder.Entity("MahoSoft.Entidades.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .UseCollation("sin_mayusculas");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("MahoSoft.Entidades.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Documento")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("TipoDocumentoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Telefono");

                    b.HasIndex("TipoDocumentoId", "Documento")
                        .IsUnique()
                        .HasFilter("\"Documento\" IS NOT NULL");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("MahoSoft.Entidades.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CondicionPago")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cufe")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Descuento")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("DocumentoId")
                        .HasColumnType("uuid");

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("FechaComprobante")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<decimal>("Iva")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("IvaPorcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Notas")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NumeroComprobante")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .UseCollation("sin_mayusculas");

                    b.Property<bool>("PreciosIncluyenIva")
                        .HasColumnType("boolean");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("TipoComprobante")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ValorComprobante")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("VendedorProveedor")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("FechaComprobante");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ProveedorId", "NumeroComprobante")
                        .IsUnique();

                    b.ToTable("Compras", t =>
                        {
                            t.HasCheckConstraint("CK_Compras_Iva", "\"IvaPorcentaje\" BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_Compras_Montos", "\"Descuento\" >= 0 AND \"Subtotal\" >= 0 AND \"Iva\" >= 0 AND \"Total\" >= 0");

                            t.HasCheckConstraint("CK_Compras_Vencimiento", "\"CondicionPago\" <> 'Credito' OR \"FechaVencimiento\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("MahoSoft.Entidades.CompraItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("CompraId")
                        .HasColumnType("integer");

                    b.Property<decimal>("CostoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<string>("ReferenciaProveedor")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("TallaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("TallaId");

                    b.ToTable("CompraItems", t =>
                        {
                            t.HasCheckConstraint("CK_CompraItems_Cantidad", "\"Cantidad\" > 0");

                            t.HasCheckConstraint("CK_CompraItems_Precios", "\"PrecioUnitario\" >= 0 AND \"CostoUnitario\" >= 0");
                        });
                });

            modelBuilder.Entity("MahoSoft.Entidades.ComprobanteTransferencia", b =>
                {
                    b.Property<int>("VentaId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ArchivoId")
                        .HasColumnType("uuid");

                    b.Property<int?>("BancoId")
                        .HasColumnType("integer");

                    b.Property<string>("Referencia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("VentaId");

                    b.HasIndex("ArchivoId");

                    b.HasIndex("BancoId");

                    b.ToTable("ComprobantesTransferencia");
                });

            modelBuilder.Entity("MahoSoft.Entidades.DescuentoPos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Porcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Porcentaje")
                        .IsUnique();

                    b.ToTable("DescuentosPos", null, t =>
                        {
                            t.HasCheckConstraint("CK_DescuentosPos_Rango", "\"Porcentaje\" BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("MahoSoft.Entidades.GrupoTalla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .UseCollation("sin_mayusculas");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("GruposTalla");
                });

            modelBuilder.Entity("MahoSoft.Entidades.MovimientoInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int?>("CompraId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<int>("TallaId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int?>("VentaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.HasIndex("Fecha");

                    b.HasIndex("TallaId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VentaId");

                    b.HasIndex("ProductoId", "TallaId");

                    b.ToTable("MovimientosInventario", null, t =>
                        {
                            t.HasCheckConstraint("CK_MovimientosInventario_Cantidad", "\"Cantidad\" <> 0");
                        });
                });

            modelBuilder.Entity("MahoSoft.Entidades.Negocio", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Correo")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Instagram")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MensajeRecibo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nit")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("StockBajoProducto")
                        .HasColumnType("integer");

                    b.Property<int>("StockBajoTalla")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Negocio", null, t =>
                        {
                            t.HasCheckConstraint("CK_Negocio_Umbrales", "\"StockBajoProducto\" >= 0 AND \"StockBajoTalla\" >= 0");

                            t.HasCheckConstraint("CK_Negocio_UnaFila", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("MahoSoft.Entidades.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("CostoActual")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("ImagenId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("PrecioVenta")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ImagenId");

                    b.ToTable("Productos", t =>
                        {
                            t.HasCheckConstraint("CK_Productos_CostoActual", "\"CostoActual\" >= 0");

                            t.HasCheckConstraint("CK_Productos_PrecioVenta", "\"PrecioVenta\" >= 0");
                        });
                });

            modelBuilder.Entity("MahoSoft.Entidades.ProductoColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .UseCollation("sin_mayusculas");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId", "Color")
                        .IsUnique();

                    b.ToTable("ProductoColores");
                });

            modelBuilder.Entity("MahoSoft.Entidades.ProductoTalla", b =>
                {
                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<int>("TallaId")
                        .HasColumnType("integer");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("ProductoId", "TallaId");

                    b.HasIndex("TallaId");

                    b.ToTable("ProductoTallas", t =>
                        {
                            t.HasCheckConstraint("CK_ProductoTallas_Stock", "\"Stock\" >= 0");
                        });
                });

            modelBuilder.Entity("MahoSoft.Entidades.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Contacto")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("IvaPorcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipoDocumentoId", "Documento")
                        .IsUnique();

                    b.ToTable("Proveedores", null, t =>
                        {
                            t.HasCheckConstraint("CK_Proveedores_Iva", "\"IvaPorcentaje\" BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("MahoSoft.Entidades.Talla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GrupoTallaId")
                        .HasColumnType("integer");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoTallaId");

                    b.HasIndex("Valor")
                        .IsUnique();

                    b.ToTable("Tallas");
                });

            modelBuilder.Entity("MahoSoft.Entidades.TipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .UseCollation("sin_mayusculas");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("TiposDocumento");
                });

            modelBuilder.Entity("MahoSoft.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Documento")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .UseCollation("sin_mayusculas");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("ResetTokenExpira")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResetTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("TipoDocumentoId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ResetTokenHash")
                        .HasFilter("\"ResetTokenHash\" IS NOT NULL");

                    b.HasIndex("TipoDocumentoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MahoSoft.Entidades.UsuarioPermiso", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Permiso")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("UsuarioId", "Permiso");

                    b.ToTable("UsuarioPermisos");
                });

            modelBuilder.Entity("MahoSoft.Entidades.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("AnuladaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AnuladaPorId")
                        .HasColumnType("integer");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Descuento")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("DescuentoPorcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("Envio")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("VendedorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnuladaPorId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Fecha");

                    b.HasIndex("NumeroFactura")
                        .IsUnique();

                    b.HasIndex("VendedorId");

                    b.ToTable("Ventas", t =>
                        {
                            t.HasCheckConstraint("CK_Ventas_Anulacion", "\"Estado\" <> 'Anulada' OR (\"AnuladaEn\" IS NOT NULL AND \"AnuladaPorId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Ventas_Descuento", "\"DescuentoPorcentaje\" BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_Ventas_Montos", "\"Envio\" >= 0 AND \"Subtotal\" >= 0 AND \"Descuento\" >= 0 AND \"Total\" >= 0");
                        });
                });

            modelBuilder.Entity("MahoSoft.Entidades.VentaEntrega", b =>
                {
                    b.Property<int>("VentaId")
                        .HasColumnType("integer");

                    b.Property<string>("Barrio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateOnly?>("FechaEntrega")
                        .HasColumnType("date");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("VentaId");

                    b.ToTable("VentaEntregas");
                });

            modelBuilder.Entity("MahoSoft.Entidades.VentaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<decimal>("CostoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<int>("TallaId")
                        .HasColumnType("integer");

                    b.Property<int>("VentaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("TallaId");

                    b.HasIndex("VentaId");

                    b.ToTable("VentaItems", t =>
                        {
                            t.HasCheckConstraint("CK_VentaItems_Cantidad", "\"Cantidad\" > 0");

                            t.HasCheckConstraint("CK_VentaItems_Precios", "\"PrecioUnitario\" >= 0 AND \"CostoUnitario\" >= 0");
                        });
                });

            modelBuilder.Entity("MahoSoft.Entidades.Cliente", b =>
                {
                    b.HasOne("MahoSoft.Entidades.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("MahoSoft.Entidades.Compra", b =>
                {
                    b.HasOne("MahoSoft.Entidades.Archivo", "Documento")
                        .WithMany()
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MahoSoft.Entidades.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MahoSoft.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Documento");

                    b.Navigation("Proveedor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MahoSoft.Entidades.CompraItem", b =>
                {
                    b.HasOne("MahoSoft.Entidades.Compra", null)
                        .WithMany("Items")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MahoSoft.Entidades.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MahoSoft.Entidades.Talla", "Talla")
                        .WithMany()
                        .HasForeignKey("TallaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Talla");
                });

            modelBuilder.Entity("MahoSoft.Entidades.ComprobanteTransferencia", b =>
                {
                    b.HasOne("MahoSoft.Entidades.Archivo", "Archivo")
                        .WithMany()
                        .HasForeignKey("ArchivoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MahoSoft.Entidades.Banco", "Banco")
                        .WithMany()
                        .HasForeignKey("BancoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MahoSoft.Entidades.Venta", null)
                        .WithOne("Comprobante")
                        .HasForeignKey("MahoSoft.Entidades.ComprobanteTransferencia", "VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Archivo");

                    b.Navigation("Banco");
                });

            modelBuilder.Entity("MahoSoft.Entidades.MovimientoInventario", b =>
                {
                    b.HasOne("MahoSoft.Entidades.Compra", "Compra")
                        .WithMany()
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MahoSoft.Entidades.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MahoSoft.Entidades.Talla", "Talla")
                        .WithMany()
                        .HasForeignKey("TallaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MahoSoft.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MahoSoft.Entidades.Venta", "Venta")
                        .WithMany()
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Compra");

                    b.Navigation("Producto");

                    b.Navigation("Talla");

                    b.Navigation("Usuario");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("MahoSoft.Entidades.Producto", b =>
                {
                    b.HasOne("MahoSoft.Entidades.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MahoSoft.Entidades.Archivo", "Imagen")
                        .WithMany()
                        .HasForeignKey("ImagenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Categoria");

                    b.Navigation("Imagen");
                });

            modelBuilder.Entity("MahoSoft.Entidades.ProductoColor", b =>
                {
                    b.HasOne("MahoSoft.Entidades.Producto", null)
                        .WithMany("Colores")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MahoSoft.Entidades.ProductoTalla", b =>
                {
                    b.HasOne("MahoSoft.Entidades.Producto", null)
                        .WithMany("Tallas")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MahoSoft.Entidades.Talla", "Talla")
                        .WithMany()
                        .HasForeignKey("TallaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Talla");
                });

            modelBuilder.Entity("MahoSoft.Entidades.Proveedor", b =>
                {
                    b.HasOne("MahoSoft.Entidades.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("MahoSoft.Entidades.Talla", b =>
                {
                    b.HasOne("MahoSoft.Entidades.GrupoTalla", "GrupoTalla")
                        .WithMany("Tallas")
                        .HasForeignKey("GrupoTallaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GrupoTalla");
                });

            modelBuilder.Entity("MahoSoft.Entidades.Usuario", b =>
                {
                    b.HasOne("MahoSoft.Entidades.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("MahoSoft.Entidades.UsuarioPermiso", b =>
                {
                    b.HasOne("MahoSoft.Entidades.Usuario", null)
                        .WithMany("Permisos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MahoSoft.Entidades.Venta", b =>
                {
                    b.HasOne("MahoSoft.Entidades.Usuario", "AnuladaPor")
                        .WithMany()
                        .HasForeignKey("AnuladaPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MahoSoft.Entidades.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MahoSoft.Entidades.Usuario", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnuladaPor");

                    b.Navigation("Cliente");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("MahoSoft.Entidades.VentaEntrega", b =>
                {
                    b.HasOne("MahoSoft.Entidades.Venta", null)
                        .WithOne("Entrega")
                        .HasForeignKey("MahoSoft.Entidades.VentaEntrega", "VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MahoSoft.Entidades.VentaItem", b =>
                {
                    b.HasOne("MahoSoft.Entidades.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MahoSoft.Entidades.Talla", "Talla")
                        .WithMany()
                        .HasForeignKey("TallaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MahoSoft.Entidades.Venta", null)
                        .WithMany("Items")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Talla");
                });

            modelBuilder.Entity("MahoSoft.Entidades.Compra", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MahoSoft.Entidades.GrupoTalla", b =>
                {
                    b.Navigation("Tallas");
                });

            modelBuilder.Entity("MahoSoft.Entidades.Producto", b =>
                {
                    b.Navigation("Colores");

                    b.Navigation("Tallas");
                });

            modelBuilder.Entity("MahoSoft.Entidades.Usuario", b =>
                {
                    b.Navigation("Permisos");
                });

            modelBuilder.Entity("MahoSoft.Entidades.Venta", b =>
                {
                    b.Navigation("Comprobante");

                    b.Navigation("Entrega");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
